# Automatically generated by RTLinux Makefile
# then hacked by trb to clean up and add uei stuff. 

prefix := $(shell /usr/realtime/bin/xeno-config --prefix)

#CWD = $(CROB_HOME)
CWD = $(shell pwd)
UEI_INC = powerdaq/include

CC = $(shell /usr/realtime/bin/xeno-config --cc)
# TODO: remove -O0 in next line
CFLAGS = $(shell /usr/realtime/bin/xeno-config --xeno-cflags) -I/opt/imt/robot/$(UEI_INC) -g -O0
## CFLAGS = $(shell xeno-config --xeno-cflags)
# FVV Removed -I/opt/imt/robot/pci4e  -I$(CWD)/../pci4e from CFLAGS  -I$(CWD)/../$(UEI_INC)
LDFLAGS = $(shell /usr/realtime/bin/xeno-config --xeno-ldflags) -lnative -lpowerdaq32 -lrtdm

# TODO: delete LINUX_DIR = /usr/src/linux
# TODO: delete RTL_DIR = $(LINUX_DIR)/rtlinux
# TODO: delete RTL_DIR = /usr/realtime
# TODO: delete UEI_INC = /usr/local/include/ueidaq

# TODO: delete INCLUDE= -I$(LINUX_DIR)/include -I$(RTL_DIR)/include -I$(RTL_DIR)/include/compat -I$(UEI_INC)
# TODO: delete CFLAGS = -D__KERNEL__ -Wall -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -pipe -march=i686 -DMODULE -g -D__RTL__ -D_LOOSE_KERNEL_NAMES -O2 $(INCLUDE) -I$(RTL_DIR)/include/posix
ARCH = i386
CC = gcc
# TODO: delete CXXFLAGS = -D__KERNEL__ -Wall -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -pipe -march=i686 -DMODULE -g -D__RTL__ -D_LOOSE_KERNEL_NAMES $(INCLUDE) -I/$(RTL_DIR)/include/posix -fno-exceptions -fno-rtti
